//! Autogenerated weights for minterest_protocol
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-07-12, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/minterest
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=minterest-protocol
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./runtime/standalone/src/weights/minterest_protocol.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for minterest_protocol.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> minterest_protocol::WeightInfo for WeightInfo<T> {
	fn create_pool() -> Weight {
		(87_065_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	fn deposit_underlying() -> Weight {
		(377_659_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(18 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn redeem() -> Weight {
		(679_513_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(41 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn redeem_underlying() -> Weight {
		(684_760_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(41 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn redeem_wrapped() -> Weight {
		(613_478_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(41 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn borrow() -> Weight {
		(502_532_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(41 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn repay() -> Weight {
		(311_289_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn repay_all() -> Weight {
		(383_516_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn repay_on_behalf() -> Weight {
		(404_917_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(17 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn transfer_wrapped() -> Weight {
		(658_338_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(42 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn enable_is_collateral() -> Weight {
		(66_933_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn disable_is_collateral() -> Weight {
		(475_116_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(31 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn claim_mnt() -> Weight {
		(1_174_850_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(35 as Weight))
			.saturating_add(T::DbWeight::get().writes(15 as Weight))
	}
}
