// This file is part of Minterest.

// Copyright (C) 2021 Minterest finance.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for chainlink_price_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-07-23, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/minterest
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=chainlink_price_manager
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/chainlink-price-manager/src/weights.rs
// --template=./templates/weight-template-for-pallet.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for chainlink_price_manager.
pub trait WeightInfo {
	fn disable_feeding() -> Weight;
	fn enable_feeding() -> Weight;
	fn initiate_new_round() -> Weight;
}

/// Weights for chainlink_price_manager using the Minterest node and recommended hardware.
pub struct MinterestWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for MinterestWeight<T> {
	fn disable_feeding() -> Weight {
		(1_072_000 as Weight)
	}
	fn enable_feeding() -> Weight {
		(1_092_000 as Weight)
	}
	fn initiate_new_round() -> Weight {
		(15_218_000 as Weight)
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn disable_feeding() -> Weight {
		(1_072_000 as Weight)
	}
	fn enable_feeding() -> Weight {
		(1_092_000 as Weight)
	}
	fn initiate_new_round() -> Weight {
		(15_218_000 as Weight)
	}
}
