// This file is part of Minterest.

// Copyright (C) 2021 Minterest finance.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for mnt_token
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-05-02, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/minterest
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=mnt_token
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/mnt-token/src/weights.rs
// --template=./templates/weight-template-for-pallet.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for mnt_token.
pub trait WeightInfo {
	fn disable_mnt_minting() -> Weight;
	fn enable_mnt_minting() -> Weight;
	fn update_speed() -> Weight;
}

/// Weights for mnt_token using the Minterest node and recommended hardware.
pub struct MinterestWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for MinterestWeight<T> {
	fn disable_mnt_minting() -> Weight {
		(286_081_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(18 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn enable_mnt_minting() -> Weight {
		(333_237_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(20 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn update_speed() -> Weight {
		(333_237_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(20 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn disable_mnt_minting() -> Weight {
		(286_081_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(18 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	fn enable_mnt_minting() -> Weight {
		(333_237_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(20 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	fn update_speed() -> Weight {
		(333_237_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(20 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
}
