[package]
name = "prices-rpc-runtime-api"
version = "0.1.0"
authors = ["Minterest developers"]
edition = "2018"

[dependencies]
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8", default-features = false }
orml-oracle = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false }

minterest-primitives = { path = "../../../../primitives", default-features = false }


[features]
default = ["std"]
std = [
    "sp-api/std",
    "sp-std/std",
    "minterest-primitives/std",
]
