//! Autogenerated weights for chainlink_price_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-07-23, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/minterest
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=chainlink_price_manager
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./runtime/src/weights/chainlink_price_manager.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for chainlink_price_manager.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> chainlink_price_manager::WeightInfo for WeightInfo<T> {
	fn disable_feeding() -> Weight {
		(1_092_000 as Weight)
	}
	fn enable_feeding() -> Weight {
		(1_082_000 as Weight)
	}
	fn initiate_new_round() -> Weight {
		(15_379_000 as Weight)
	}
}
