//! Autogenerated weights for minterest_protocol
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-06-09, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/minterest
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=minterest_protocol
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./runtime/src/weights/minterest_protocol.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for minterest_protocol.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> minterest_protocol::WeightInfo for WeightInfo<T> {
	fn create_pool() -> Weight {
		(95_184_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	fn deposit_underlying() -> Weight {
		(402_168_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(18 as Weight))
			.saturating_add(T::DbWeight::get().writes(12 as Weight))
	}
	fn redeem() -> Weight {
		(616_457_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(40 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn redeem_underlying() -> Weight {
		(625_034_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(40 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn redeem_wrapped() -> Weight {
		(609_887_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(40 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn borrow() -> Weight {
		(669_931_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(40 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn repay() -> Weight {
		(371_839_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn repay_all() -> Weight {
		(371_930_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn repay_on_behalf() -> Weight {
		(370_784_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn transfer_wrapped() -> Weight {
		(586_892_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(42 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn enable_is_collateral() -> Weight {
		(55_335_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn disable_is_collateral() -> Weight {
		(316_365_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(30 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn claim_mnt() -> Weight {
		(1_026_880_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(35 as Weight))
			.saturating_add(T::DbWeight::get().writes(15 as Weight))
	}
}
