
//! Autogenerated weights for minterest_protocol
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-04-26, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/minterest
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=minterest_protocol
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./runtime/src/weights/minterest_protocol.rs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for minterest_protocol.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> minterest_protocol::WeightInfo for WeightInfo<T> {
	fn deposit_underlying() -> Weight {
		(274_921_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(17 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	fn redeem() -> Weight {
		(549_471_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(39 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn redeem_underlying() -> Weight {
		(546_380_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(39 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn redeem_wrapped() -> Weight {
		(529_252_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(39 as Weight))
			.saturating_add(T::DbWeight::get().writes(10 as Weight))
	}
	fn borrow() -> Weight {
		(464_650_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(37 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn repay() -> Weight {
		(212_322_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(13 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn repay_all() -> Weight {
		(212_250_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(13 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn repay_on_behalf() -> Weight {
		(206_991_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(13 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn transfer_wrapped() -> Weight {
		(464_942_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(40 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	fn enable_is_collateral() -> Weight {
		(53_132_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn disable_is_collateral() -> Weight {
		(300_315_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(30 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn claim_mnt() -> Weight {
		(1_064_030_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(35 as Weight))
			.saturating_add(T::DbWeight::get().writes(15 as Weight))
	}
}
